services:
  - type: web
    name: triviall
    runtime: static
    buildCommand: npm install && npm run build:web
    staticPublishPath: ./dist
    envVars:
      - key: EXPO_PUBLIC_GEMINI_API_KEY
        sync: false
      - key: EXPO_PUBLIC_SUPABASE_URL
        sync: false
      - key: EXPO_PUBLIC_SUPABASE_ANON_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
